language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - 12
  - 10
git:
  depth:
    1


jobs:
  include:
    - stage: lint
      node_js: "node"
      script: npm run lint
    - stage: coverage
      node_js: "node"
      script: npm run coverage
      after_script: npm run coverage:report
